# Generated by Django 4.1.7 on 2023-06-28 12:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutSections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ID", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                (
                    "richText",
                    ckeditor.fields.RichTextField(
                        default="Écrire ici",
                        max_length=10000,
                        verbose_name="Contenu de la section",
                    ),
                ),
                ("custom_html", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="", verbose_name="Image de la section"
                    ),
                ),
                ("image_title", models.CharField(blank=True, max_length=50)),
                ("image_alt", models.CharField(blank=True, max_length=50)),
                (
                    "reverse",
                    models.BooleanField(
                        default=False,
                        verbose_name="Inverser l'ordre de l'image et du texte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page à propos",
                "verbose_name_plural": "Page à propos",
            },
        ),
        migrations.CreateModel(
            name="AssoSections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ID", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                (
                    "richText",
                    ckeditor.fields.RichTextField(
                        default="Écrire ici",
                        max_length=10000,
                        verbose_name="Contenu de la section",
                    ),
                ),
                ("custom_html", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="", verbose_name="Image de la section"
                    ),
                ),
                ("image_title", models.CharField(blank=True, max_length=50)),
                ("image_alt", models.CharField(blank=True, max_length=50)),
                (
                    "reverse",
                    models.BooleanField(
                        default=False,
                        verbose_name="Inverser l'ordre de l'image et du texte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page association",
                "verbose_name_plural": "Page association",
            },
        ),
        migrations.CreateModel(
            name="AssoStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Titre du statut"),
                ),
                (
                    "richText",
                    ckeditor.fields.RichTextField(verbose_name="Texte du statut"),
                ),
            ],
            options={
                "verbose_name": "Statut de l'association",
                "verbose_name_plural": "Statuts de l'association",
            },
        ),
        migrations.CreateModel(
            name="BaseRessources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Titre de la section"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=500,
                        verbose_name="Description de la ressource (max 500 caractères)",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Adresse de la ressource",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Numéro de téléphone de la ressource",
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, verbose_name="Lien vers la ressource"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="DefaultRessources.jpg",
                        upload_to="",
                        verbose_name="Image de la section",
                    ),
                ),
                (
                    "image_title",
                    models.CharField(
                        blank=True,
                        default="Default image",
                        max_length=50,
                        verbose_name="Titre de l'image",
                    ),
                ),
                (
                    "image_alt",
                    models.CharField(
                        blank=True,
                        default="Default image",
                        max_length=50,
                        verbose_name="Texte alternatif de l'image",
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        max_length=100,
                        verbose_name="Mots-clés (séparés par des virgules)",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChronicTabSections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="Laisser vide pour ajouter la section à la fin ou mettre 0 pour ne pas afficher la section",
                        null=True,
                        verbose_name="Ordre de la section",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Titre de la section"
                    ),
                ),
                (
                    "richText",
                    ckeditor.fields.RichTextField(verbose_name="Contenu de la section"),
                ),
                ("custom_html", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="", verbose_name="Image de la section"
                    ),
                ),
                (
                    "image_title",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Titre de l'image"
                    ),
                ),
                (
                    "image_alt",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Texte alternatif de l'image",
                    ),
                ),
                (
                    "reverse",
                    models.BooleanField(
                        default=False,
                        verbose_name="Inverser l'ordre de l'image et du texte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maladies chroniques",
                "verbose_name_plural": "Maladies chroniques",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ContactSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Titre de la section"),
                ),
                (
                    "text",
                    models.TextField(
                        max_length=500,
                        verbose_name="Texte de la section (max 500 caractères)",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Nom du contact"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email du contact"),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20, verbose_name="Numéro de téléphone du contact"
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=100, verbose_name="Adresse du contact"),
                ),
            ],
            options={
                "verbose_name": "Section Contact",
                "verbose_name_plural": "Section Contact",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Titre de l'évènement"
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        max_length=300,
                        verbose_name="Description courte de l'évènement (max 300 caractères)",
                    ),
                ),
                (
                    "full_description",
                    ckeditor.fields.RichTextField(
                        verbose_name="Description complète de l'évènement"
                    ),
                ),
                ("date", models.DateField(verbose_name="Date de l'évènement")),
                (
                    "start_time",
                    models.TimeField(
                        default="00:00", verbose_name="Heure de début de l'évènement"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        default="01:00", verbose_name="Heure de fin de l'évènement"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Adresse de l'évènement",
                    ),
                ),
                ("link", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Rendez-vous",
                "verbose_name_plural": "Rendez-vous",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="HomeSections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ID", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                (
                    "richText",
                    ckeditor.fields.RichTextField(
                        default="Écrire ici",
                        max_length=10000,
                        verbose_name="Contenu de la section",
                    ),
                ),
                ("custom_html", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="", verbose_name="Image de la section"
                    ),
                ),
                ("image_title", models.CharField(blank=True, max_length=50)),
                ("image_alt", models.CharField(blank=True, max_length=50)),
                (
                    "reverse",
                    models.BooleanField(
                        default=False,
                        verbose_name="Inverser l'ordre de l'image et du texte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page d'accueil",
                "verbose_name_plural": "Page d'accueil",
            },
        ),
        migrations.CreateModel(
            name="InvsibleTabSections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="Laisser vide pour ajouter la section à la fin ou mettre 0 pour ne pas afficher la section",
                        null=True,
                        verbose_name="Ordre de la section",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Titre de la section"
                    ),
                ),
                (
                    "richText",
                    ckeditor.fields.RichTextField(verbose_name="Contenu de la section"),
                ),
                ("custom_html", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="", verbose_name="Image de la section"
                    ),
                ),
                (
                    "image_title",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Titre de l'image"
                    ),
                ),
                (
                    "image_alt",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Texte alternatif de l'image",
                    ),
                ),
                (
                    "reverse",
                    models.BooleanField(
                        default=False,
                        verbose_name="Inverser l'ordre de l'image et du texte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maladies invisibles",
                "verbose_name_plural": "Maladies invisibles",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="MiscarriageTabSections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="Laisser vide pour ajouter la section à la fin ou mettre 0 pour ne pas afficher la section",
                        null=True,
                        verbose_name="Ordre de la section",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Titre de la section"
                    ),
                ),
                (
                    "richText",
                    ckeditor.fields.RichTextField(verbose_name="Contenu de la section"),
                ),
                ("custom_html", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="", verbose_name="Image de la section"
                    ),
                ),
                (
                    "image_title",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Titre de l'image"
                    ),
                ),
                (
                    "image_alt",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Texte alternatif de l'image",
                    ),
                ),
                (
                    "reverse",
                    models.BooleanField(
                        default=False,
                        verbose_name="Inverser l'ordre de l'image et du texte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fausses couches",
                "verbose_name_plural": "Fausses couches",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="YoutubeVideos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("video_url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="AdminRessources",
            fields=[
                (
                    "baseressources_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="website.baseressources",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ressources administratives",
                "verbose_name_plural": "Ressources administratives",
            },
            bases=("website.baseressources",),
        ),
        migrations.CreateModel(
            name="FinancialRessources",
            fields=[
                (
                    "baseressources_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="website.baseressources",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ressources financières",
                "verbose_name_plural": "Ressources financières",
            },
            bases=("website.baseressources",),
        ),
        migrations.CreateModel(
            name="TherapeuticRessources",
            fields=[
                (
                    "baseressources_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="website.baseressources",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ressources thérapeutiques",
                "verbose_name_plural": "Ressources thérapeutiques",
            },
            bases=("website.baseressources",),
        ),
    ]
