# Generated by Django 4.1.7 on 2023-07-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "website",
            "0002_aboutsections_remote_image_assosections_remote_image_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutsections",
            name="image",
        ),
        migrations.RemoveField(
            model_name="assosections",
            name="image",
        ),
        migrations.RemoveField(
            model_name="homesections",
            name="image",
        ),
    ]
