# Generated by Django 4.1.7 on 2023-05-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_webpagesection_custom_html_webpagesection_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webpagesection",
            name="image",
            field=models.ImageField(upload_to="medias/"),
        ),
    ]
