# Generated by Django 4.1.7 on 2023-07-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "website",
            "0003_remove_aboutsections_image_remove_assosections_image_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="aboutsections",
            old_name="remote_image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="assosections",
            old_name="remote_image",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="homesections",
            old_name="remote_image",
            new_name="image",
        ),
    ]
