# Generated by Django 4.1.7 on 2023-07-05 13:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_rename_remote_image_aboutsections_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseressources",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="chronictabsections",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="invsibletabsections",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="miscarriagetabsections",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, verbose_name="image"
            ),
        ),
    ]
