# Generated by Django 4.1.7 on 2023-05-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0005_alter_webpagesection_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpagesection",
            name="image_alt",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
