# Generated by Django 4.1.7 on 2023-10-12 12:57

import ckeditor.fields
import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_membershipsection"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ID", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                (
                    "richText",
                    ckeditor.fields.RichTextField(
                        default="Écrire ici",
                        max_length=10000,
                        verbose_name="Contenu de la section",
                    ),
                ),
                ("custom_html", models.TextField(blank=True)),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, verbose_name="image"
                    ),
                ),
                ("image_title", models.CharField(blank=True, max_length=50)),
                ("image_alt", models.CharField(blank=True, max_length=50)),
                (
                    "reverse",
                    models.BooleanField(
                        default=False,
                        verbose_name="Inverser l'ordre de l'image et du texte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page Dons",
                "verbose_name_plural": "Page Dons",
            },
        ),
        migrations.AlterModelOptions(
            name="membershipsection",
            options={
                "verbose_name": "Page Adhésion",
                "verbose_name_plural": "Page Adhésion",
            },
        ),
    ]
