# Generated by Django 4.1.7 on 2023-05-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_webpagesection_image_alt"),
    ]

    operations = [
        migrations.AddField(
            model_name="webpagesection",
            name="image_title",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
