# Generated by Django 4.1.7 on 2023-06-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_webpagesection_image_title"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WebpageSection",
            new_name="HomePageSections",
        ),
    ]
