# Generated by Django 4.1.7 on 2024-07-15 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_alter_financialressources_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventParticipants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="website.event"
                    ),
                ),
            ],
            options={
                "verbose_name": "Participation",
                "verbose_name_plural": "Participations",
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50, verbose_name="Nom")),
                ("lname", models.CharField(max_length=50, verbose_name="Prénom")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("address", models.CharField(max_length=100, verbose_name="Adresse")),
                (
                    "zip_code",
                    models.CharField(max_length=100, verbose_name="Code postal"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "event",
                    models.ManyToManyField(
                        related_name="participants",
                        through="website.EventParticipants",
                        to="website.event",
                        verbose_name="Évènement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Participant",
                "verbose_name_plural": "Participants",
            },
        ),
        migrations.AddField(
            model_name="eventparticipants",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="website.participant"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="eventparticipants",
            unique_together={("event", "participant")},
        ),
    ]
