# Generated by Django 4.1.7 on 2023-06-07 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_youtubevideo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="YoutubeVideo",
            new_name="YoutubeVideos",
        ),
    ]
