# Generated by Django 4.1.7 on 2024-07-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_event_is_talk_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="participant",
            name="event",
        ),
        migrations.AddField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                related_name="events",
                through="website.EventParticipants",
                to="website.participant",
                verbose_name="Participants",
            ),
        ),
    ]
