# Generated by Django 4.1.7 on 2023-06-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0011_rename_youtubevideo_youtubevideos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="youtubevideos",
            name="title",
        ),
        migrations.AlterField(
            model_name="youtubevideos",
            name="short_url",
            field=models.URLField(),
        ),
    ]
