# Generated by Django 4.1.7 on 2023-06-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0012_remove_youtubevideos_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubevideos",
            name="title",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
