# Generated by Django 4.1.7 on 2024-07-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0012_alter_participant_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "verbose_name": "Rendez-vous",
                "verbose_name_plural": "Rendez-vous",
            },
        ),
        migrations.AddField(
            model_name="eventparticipants",
            name="isFullyBooked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_talk_event",
            field=models.BooleanField(default=False, verbose_name="Groupe de parole"),
        ),
    ]
