# Generated by Django 4.1.7 on 2024-07-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "website",
            "0013_alter_event_options_eventparticipants_isfullybooked_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="participants_limit",
            field=models.PositiveIntegerField(
                default=10,
                verbose_name="Nombre maximum de participants (groupe de parole)",
            ),
        ),
    ]
