# Generated by Django 4.1.7 on 2023-06-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0013_youtubevideos_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="youtubevideos",
            old_name="short_url",
            new_name="video_url",
        ),
    ]
