# Generated by Django 4.1.7 on 2023-06-07 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_rename_short_url_youtubevideos_video_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssociationSections",
            fields=[
                (
                    "homepagesections_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="website.homepagesections",
                    ),
                ),
            ],
            bases=("website.homepagesections",),
        ),
    ]
