# Generated by Django 4.1.7 on 2024-07-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0014_event_participants_limit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventparticipants",
            name="isFullyBooked",
        ),
        migrations.AddField(
            model_name="event",
            name="isFullyBooked",
            field=models.BooleanField(default=False),
        ),
    ]
