# Generated by Django 4.1.7 on 2023-06-09 14:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0015_associationsections"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThematicSections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("bodyText", ckeditor.fields.RichTextField()),
            ],
        ),
    ]
