# Generated by Django 5.0.7 on 2024-08-16 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0016_rename_isfullybooked_event_is_fully_booked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="is_fully_booked",
            field=models.BooleanField(default=False, verbose_name="Évènement complet"),
        ),
        migrations.AlterField(
            model_name="event",
            name="participants_limit",
            field=models.PositiveIntegerField(
                default=9,
                verbose_name="Nombre maximum de participants (groupe de parole)",
            ),
        ),
    ]
