# Generated by Django 4.1.7 on 2023-06-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0016_thematicsections"),
    ]

    operations = [
        migrations.AddField(
            model_name="thematicsections",
            name="tab",
            field=models.CharField(
                choices=[
                    ("chronique", "Chronique"),
                    ("invisible", "Invisible"),
                    ("fausseCouche", "Fausse-couche"),
                ],
                default="chronique",
                max_length=20,
            ),
        ),
    ]
