# Generated by Django 4.1.7 on 2023-06-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0017_thematicsections_tab"),
    ]

    operations = [
        migrations.RenameField(
            model_name="thematicsections",
            old_name="bodyText",
            new_name="content_html",
        ),
        migrations.AddField(
            model_name="thematicsections",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="", verbose_name="Image de la section"
            ),
        ),
        migrations.AddField(
            model_name="thematicsections",
            name="image_alt",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Texte alternatif de l'image"
            ),
        ),
        migrations.AddField(
            model_name="thematicsections",
            name="image_title",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Titre de l'image"
            ),
        ),
        migrations.AddField(
            model_name="thematicsections",
            name="reverse",
            field=models.BooleanField(
                default=False, verbose_name="Inverser l'ordre de l'image et du texte"
            ),
        ),
        migrations.AlterField(
            model_name="thematicsections",
            name="title",
            field=models.CharField(max_length=100, verbose_name="Titre de la section"),
        ),
    ]
