# Generated by Django 5.0.7 on 2024-08-23 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0018_participant_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="short_description",
            field=models.TextField(
                default="Évènement sans description",
                max_length=300,
                verbose_name="Description courte de l'évènement (max 300 caractères)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(
                default="Évènement sans titre",
                max_length=100,
                verbose_name="Titre de l'évènement",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="fname",
            field=models.CharField(max_length=50, verbose_name="Prénom"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="lname",
            field=models.CharField(max_length=50, verbose_name="Nom"),
        ),
    ]
