# Generated by Django 4.1.7 on 2023-06-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0019_alter_thematicsections_content_html_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="thematicsections",
            old_name="content_html",
            new_name="richText",
        ),
        migrations.AddField(
            model_name="thematicsections",
            name="custom_html",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="thematicsections",
            name="tab",
            field=models.CharField(
                choices=[
                    ("chronic", "Maladies chroniques"),
                    ("invisible", "Maladies invisibles"),
                    ("miscarriage", "Fausses couches"),
                ],
                default="chronic",
                max_length=20,
                verbose_name="Onglet associé",
            ),
        ),
    ]
