# Generated by Django 5.0.7 on 2024-08-23 13:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0019_alter_event_short_description_alter_event_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="full_description",
            field=ckeditor.fields.RichTextField(
                default="Description complète de l'évènement",
                verbose_name="Description complète de l'évènement",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="short_description",
            field=models.TextField(
                default="Description courte de l'évènement",
                max_length=300,
                verbose_name="Description courte de l'évènement (max 300 caractères)",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(
                default="Titre de l'évènement",
                max_length=100,
                verbose_name="Titre de l'évènement",
            ),
        ),
    ]
