# Generated by Django 5.0.7 on 2024-08-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0020_alter_event_full_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="country",
            field=models.CharField(default="N/A", max_length=100, verbose_name="Pays"),
        ),
    ]
