# Generated by Django 4.1.7 on 2023-06-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0020_rename_content_html_thematicsections_richtext_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="thematicsections",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="thematicsections",
            name="order",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ordre de la section"
            ),
        ),
    ]
