# Generated by Django 4.1.7 on 2023-06-12 13:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0023_alter_chronictabsections_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InvsibleTabSections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="Laisser vide pour ajouter la section à la fin ou mettre 0 pour ne pas afficher la section",
                        null=True,
                        verbose_name="Ordre de la section",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Titre de la section"
                    ),
                ),
                (
                    "richText",
                    ckeditor.fields.RichTextField(verbose_name="Contenu de la section"),
                ),
                ("custom_html", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="", verbose_name="Image de la section"
                    ),
                ),
                (
                    "image_title",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Titre de l'image"
                    ),
                ),
                (
                    "image_alt",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Texte alternatif de l'image",
                    ),
                ),
                (
                    "reverse",
                    models.BooleanField(
                        default=False,
                        verbose_name="Inverser l'ordre de l'image et du texte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maladies invisibles",
                "verbose_name_plural": "Maladies invisibles",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="MiscarriageTabSections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        blank=True,
                        default=None,
                        help_text="Laisser vide pour ajouter la section à la fin ou mettre 0 pour ne pas afficher la section",
                        null=True,
                        verbose_name="Ordre de la section",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Titre de la section"
                    ),
                ),
                (
                    "richText",
                    ckeditor.fields.RichTextField(verbose_name="Contenu de la section"),
                ),
                ("custom_html", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="", verbose_name="Image de la section"
                    ),
                ),
                (
                    "image_title",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Titre de l'image"
                    ),
                ),
                (
                    "image_alt",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Texte alternatif de l'image",
                    ),
                ),
                (
                    "reverse",
                    models.BooleanField(
                        default=False,
                        verbose_name="Inverser l'ordre de l'image et du texte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fausses couches",
                "verbose_name_plural": "Fausses couches",
                "ordering": ["order"],
            },
        ),
    ]
