# Generated by Django 4.1.7 on 2023-06-13 14:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0024_invsibletabsections_miscarriagetabsections"),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseRessources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Titre de la section"
                    ),
                ),
                (
                    "description",
                    ckeditor.fields.RichTextField(verbose_name="Contenu de la section"),
                ),
                ("url", models.URLField(verbose_name="Lien vers la ressource")),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="", verbose_name="Image de la section"
                    ),
                ),
                (
                    "image_title",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Titre de l'image"
                    ),
                ),
                (
                    "image_alt",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Texte alternatif de l'image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminRessources",
            fields=[
                (
                    "baseressources_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="website.baseressources",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ressources administratives",
                "verbose_name_plural": "Ressources administratives",
            },
            bases=("website.baseressources",),
        ),
        migrations.CreateModel(
            name="FinancialRessources",
            fields=[
                (
                    "baseressources_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="website.baseressources",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ressources financières",
                "verbose_name_plural": "Ressources financières",
            },
            bases=("website.baseressources",),
        ),
        migrations.CreateModel(
            name="TherapeuticRessources",
            fields=[
                (
                    "baseressources_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="website.baseressources",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ressources thérapeutiques",
                "verbose_name_plural": "Ressources thérapeutiques",
            },
            bases=("website.baseressources",),
        ),
    ]
