# Generated by Django 5.0.7 on 2024-10-15 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0024_talkeventexplanationsection"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipPlans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nom du plan")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        verbose_name="Description du plan (max 500 caractères)",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=6, verbose_name="Prix du plan"
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[("yearly", "Annuel"), ("monthly", "Mensuel")],
                        default="Annuel",
                        max_length=50,
                        verbose_name="Fréquence de paiement",
                    ),
                ),
                (
                    "lookup_key",
                    models.CharField(max_length=50, verbose_name="Clé de recherche"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50, verbose_name="Prénom")),
                ("lname", models.CharField(max_length=50, verbose_name="Nom")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Numéro de téléphone"
                    ),
                ),
                ("birthdate", models.DateField(verbose_name="Date de naissance")),
                ("address", models.CharField(max_length=100, verbose_name="Adresse")),
                (
                    "zip_code",
                    models.CharField(max_length=100, verbose_name="Code postal"),
                ),
                ("city", models.CharField(max_length=100, verbose_name="Ville")),
                (
                    "country",
                    models.CharField(
                        default="N/A", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "join_date",
                    models.DateField(auto_now_add=True, verbose_name="Date d'adhésion"),
                ),
                (
                    "membership_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.membershipplans",
                        verbose_name="Plan d'adhésion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membre",
                "verbose_name_plural": "Membres",
            },
        ),
    ]
