# Generated by Django 5.0.7 on 2024-10-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0025_membershipplans_members"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminressources",
            options={
                "verbose_name": "Page Ressources - Administratives",
                "verbose_name_plural": "Page Ressources - Administratives",
            },
        ),
        migrations.AlterModelOptions(
            name="assostatus",
            options={
                "verbose_name": "Page statut de l'association",
                "verbose_name_plural": "Page statuts de l'association",
            },
        ),
        migrations.AlterModelOptions(
            name="chronictabsections",
            options={
                "ordering": ["order"],
                "verbose_name": "Page Thématiques - Maladies chroniques",
                "verbose_name_plural": "Page Thématiques - Maladies chroniques",
            },
        ),
        migrations.AlterModelOptions(
            name="contactsection",
            options={
                "verbose_name": "Pag contact",
                "verbose_name_plural": "Page contact",
            },
        ),
        migrations.AlterModelOptions(
            name="financialressources",
            options={
                "verbose_name": "Page Ressources - Bibliothèque",
                "verbose_name_plural": "Page Ressources - Bibliothèque",
            },
        ),
        migrations.AlterModelOptions(
            name="invsibletabsections",
            options={
                "ordering": ["order"],
                "verbose_name": "Page Thématiques - Maladies invisibles",
                "verbose_name_plural": "Page Thématiques - Maladies invisibles",
            },
        ),
        migrations.AlterModelOptions(
            name="membershipplans",
            options={
                "verbose_name": "Plan d'adhésion",
                "verbose_name_plural": "Plans d'adhésion",
            },
        ),
        migrations.AlterModelOptions(
            name="therapeuticressources",
            options={
                "verbose_name": "Page Ressources - Thérapeutiques",
                "verbose_name_plural": "Page Ressources - Thérapeutiques",
            },
        ),
        migrations.AlterField(
            model_name="membershipplans",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="Prix du plan (CHF)"
            ),
        ),
    ]
