# Generated by Django 4.1.7 on 2023-06-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0025_baseressources_adminressources_financialressources_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseressources",
            name="address",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Adresse de la ressource"
            ),
        ),
    ]
