# Generated by Django 4.1.7 on 2023-06-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0026_baseressources_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="baseressources",
            name="description",
            field=models.TextField(verbose_name="Description de la ressource"),
        ),
        migrations.AlterField(
            model_name="baseressources",
            name="url",
            field=models.URLField(blank=True, verbose_name="Lien vers la ressource"),
        ),
    ]
