# Generated by Django 4.1.7 on 2023-06-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0027_alter_baseressources_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseressources",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                verbose_name="Numéro de téléphone de la ressource",
            ),
        ),
        migrations.AlterField(
            model_name="baseressources",
            name="description",
            field=models.TextField(
                max_length=500,
                verbose_name="Description de la ressource (max 500 caractères)",
            ),
        ),
        migrations.AlterField(
            model_name="baseressources",
            name="image",
            field=models.ImageField(
                blank=True,
                default="DefaultPic.jpg",
                upload_to="",
                verbose_name="Image de la section",
            ),
        ),
        migrations.AlterField(
            model_name="baseressources",
            name="image_alt",
            field=models.CharField(
                blank=True,
                default="Default image",
                max_length=50,
                verbose_name="Texte alternatif de l'image",
            ),
        ),
        migrations.AlterField(
            model_name="baseressources",
            name="image_title",
            field=models.CharField(
                blank=True,
                default="Default image",
                max_length=50,
                verbose_name="Titre de l'image",
            ),
        ),
    ]
