# Generated by Django 5.0.7 on 2024-10-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0027_alter_membershipplans_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipplans",
            name="lookup_key",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="Clé de recherche"
            ),
        ),
    ]
