# Generated by Django 5.0.7 on 2024-10-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0028_alter_membershipplans_lookup_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="is_subcribtion_active",
            field=models.BooleanField(default=True, verbose_name="Adhésion active"),
        ),
    ]
