# Generated by Django 4.1.7 on 2023-06-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0029_rename_url_baseressources_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="baseressources",
            name="keywords",
            field=models.CharField(
                blank=True,
                max_length=100,
                verbose_name="Mots-clés (séparés par des virgules)",
            ),
        ),
        migrations.AlterField(
            model_name="baseressources",
            name="image",
            field=models.ImageField(
                blank=True,
                default="DefaultRessources.jpg",
                upload_to="",
                verbose_name="Image de la section",
            ),
        ),
    ]
