# Generated by Django 5.0.7 on 2024-10-15 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0029_members_is_subcribtion_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="members",
            old_name="is_subcribtion_active",
            new_name="is_subscription_active",
        ),
    ]
