# Generated by Django 5.0.7 on 2024-10-16 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0030_rename_is_subcribtion_active_members_is_subscription_active"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FinancialRessources",
            new_name="LibraryRessources",
        ),
    ]
