# Generated by Django 4.1.7 on 2023-06-19 10:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0030_baseressources_keywords_alter_baseressources_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, verbose_name="Titre de l'évènement"
                    ),
                ),
                (
                    "short_description",
                    models.TextField(
                        max_length=300,
                        verbose_name="Description courte de l'évènement (max 300 caractères)",
                    ),
                ),
                (
                    "full_description",
                    ckeditor.fields.RichTextField(
                        verbose_name="Description complète de l'évènement"
                    ),
                ),
                ("date", models.DateField(verbose_name="Date de l'évènement")),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Adresse de l'évènement",
                    ),
                ),
                ("link", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Rendez-vous",
                "verbose_name_plural": "Rendez-vous",
                "ordering": ["-date"],
            },
        ),
        migrations.AlterField(
            model_name="baseressources",
            name="keywords",
            field=models.CharField(
                max_length=100, verbose_name="Mots-clés (séparés par des virgules)"
            ),
        ),
    ]
