# Generated by Django 4.1.7 on 2023-06-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0031_event_alter_baseressources_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="end_time",
            field=models.TimeField(
                default="01:00", verbose_name="Heure de fin de l'évènement"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="start_time",
            field=models.TimeField(
                default="00:00", verbose_name="Heure de début de l'évènement"
            ),
        ),
    ]
