# Generated by Django 5.0.7 on 2024-10-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0031_rename_financialressources_libraryressources"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="payment_info_country",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Pays pour le paiement"
            ),
        ),
        migrations.AddField(
            model_name="members",
            name="payment_info_name",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Nom pour le paiement"
            ),
        ),
        migrations.AddField(
            model_name="members",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, max_length=250, verbose_name="ID client Stripe"
            ),
        ),
    ]
