# Generated by Django 4.1.7 on 2023-06-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0032_event_end_time_event_start_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Titre de la section"),
                ),
                (
                    "text",
                    models.TextField(
                        max_length=500,
                        verbose_name="Texte de la section (max 500 caractères)",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Nom du contact"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Email du contact"),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20, verbose_name="Numéro de téléphone du contact"
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=100, verbose_name="Adresse du contact"),
                ),
            ],
        ),
    ]
