# Generated by Django 5.0.7 on 2024-10-17 09:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0032_members_payment_info_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Volunteers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fname", models.CharField(max_length=50, verbose_name="Prénom")),
                ("lname", models.CharField(max_length=50, verbose_name="Nom")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Numéro de téléphone"
                    ),
                ),
                (
                    "birthdate",
                    models.DateField(blank=True, verbose_name="Date de naissance"),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Adresse"
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Code postal"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Ville"),
                ),
                (
                    "country",
                    models.CharField(
                        default="N/A", max_length=100, verbose_name="Pays"
                    ),
                ),
                (
                    "occupation",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Profession"
                    ),
                ),
                (
                    "role",
                    models.CharField(blank=True, max_length=100, verbose_name="Rôle"),
                ),
                (
                    "team",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("team1", "Team 1"),
                            ("team2", "Team 2"),
                            ("team3", "Team 3"),
                        ],
                        max_length=100,
                        verbose_name="Équipe",
                    ),
                ),
                (
                    "notes",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        max_length=3000,
                        verbose_name="Notes (max 3000 caractères)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Volontaire actif"),
                ),
                (
                    "join_date",
                    models.DateField(
                        auto_now_add=True, verbose_name="Date de la prise de fonction"
                    ),
                ),
            ],
            options={
                "verbose_name": "BDD - Volontaire",
                "verbose_name_plural": "BDD - Volontaires",
            },
        ),
        migrations.AlterModelOptions(
            name="aboutsections",
            options={
                "verbose_name": "Page - À propos",
                "verbose_name_plural": "Page - À propos",
            },
        ),
        migrations.AlterModelOptions(
            name="adminressources",
            options={
                "verbose_name": "Page - Ressources: Administratives",
                "verbose_name_plural": "Page - Ressources: Administratives",
            },
        ),
        migrations.AlterModelOptions(
            name="assosections",
            options={
                "verbose_name": "Page - Association",
                "verbose_name_plural": "Page - Association",
            },
        ),
        migrations.AlterModelOptions(
            name="assostatus",
            options={
                "verbose_name": "Page - Statut de l'association",
                "verbose_name_plural": "Page - Statuts de l'association",
            },
        ),
        migrations.AlterModelOptions(
            name="chronictabsections",
            options={
                "ordering": ["order"],
                "verbose_name": "Page - Thématiques: Maladies chroniques",
                "verbose_name_plural": "Page - Thématiques: Maladies chroniques",
            },
        ),
        migrations.AlterModelOptions(
            name="contactsection",
            options={
                "verbose_name": "Page - Contact",
                "verbose_name_plural": "Page - Contact",
            },
        ),
        migrations.AlterModelOptions(
            name="donationsection",
            options={
                "verbose_name": "Page - Dons",
                "verbose_name_plural": "Page - Dons",
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "verbose_name": "BDD - Rendez-vous",
                "verbose_name_plural": "BDD - Rendez-vous",
            },
        ),
        migrations.AlterModelOptions(
            name="eventparticipants",
            options={
                "verbose_name": "BDD - Participation",
                "verbose_name_plural": "BDD - Participations",
            },
        ),
        migrations.AlterModelOptions(
            name="homesections",
            options={
                "verbose_name": "Page - Accueil",
                "verbose_name_plural": "Page - Accueil",
            },
        ),
        migrations.AlterModelOptions(
            name="invsibletabsections",
            options={
                "ordering": ["order"],
                "verbose_name": "Page - Thématiques: Maladies invisibles",
                "verbose_name_plural": "Page - Thématiques: Maladies invisibles",
            },
        ),
        migrations.AlterModelOptions(
            name="libraryressources",
            options={
                "verbose_name": "Page - Ressources: Bibliothèque",
                "verbose_name_plural": "Page - Ressources: Bibliothèque",
            },
        ),
        migrations.AlterModelOptions(
            name="members",
            options={
                "verbose_name": "BDD - Membre",
                "verbose_name_plural": "BDD - Membres",
            },
        ),
        migrations.AlterModelOptions(
            name="membershipplans",
            options={
                "verbose_name": "BDD - Plan d'adhésion",
                "verbose_name_plural": "BDD - Plans d'adhésion",
            },
        ),
        migrations.AlterModelOptions(
            name="membershipsection",
            options={
                "verbose_name": "Page - Adhésion membre",
                "verbose_name_plural": "Page - Adhésion membres",
            },
        ),
        migrations.AlterModelOptions(
            name="participant",
            options={
                "verbose_name": "BDD - Participant",
                "verbose_name_plural": "BDD - Participants",
            },
        ),
        migrations.AlterModelOptions(
            name="talkeventexplanationsection",
            options={
                "verbose_name": "Page - Inscription aux groupes de parole",
                "verbose_name_plural": "Page - Inscription aux groupes de parole",
            },
        ),
        migrations.AlterModelOptions(
            name="therapeuticressources",
            options={
                "verbose_name": "Page - Ressources: Thérapeutiques",
                "verbose_name_plural": "Page - Ressources: Thérapeutiques",
            },
        ),
        migrations.AlterModelOptions(
            name="youtubevideos",
            options={
                "verbose_name": "Lien - Vidéo Youtube",
                "verbose_name_plural": "Liens - Vidéos Youtube",
            },
        ),
    ]
