# Generated by Django 4.1.7 on 2023-06-21 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0033_contacttext"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ContactText",
            new_name="ContactSection",
        ),
        migrations.AlterModelOptions(
            name="contactsection",
            options={"verbose_name": "Contact", "verbose_name_plural": "Contact"},
        ),
    ]
