# Generated by Django 5.0.7 on 2024-10-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0034_alter_volunteers_birthdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteers",
            name="role",
            field=models.CharField(
                blank=True, default="N/A", max_length=100, verbose_name="Rôle"
            ),
        ),
    ]
