# Generated by Django 4.1.7 on 2023-06-21 12:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0034_rename_contacttext_contactsection_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactsection",
            options={
                "verbose_name": "Section Contact",
                "verbose_name_plural": "Section Contact",
            },
        ),
        migrations.AddField(
            model_name="homepagesections",
            name="richText",
            field=ckeditor.fields.RichTextField(
                default="Some Text",
                max_length=10000,
                verbose_name="Contenu de la section",
            ),
        ),
    ]
