# Generated by Django 4.1.7 on 2023-06-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0035_alter_contactsection_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagesections",
            name="reverse",
            field=models.BooleanField(
                default=False, verbose_name="Inverser l'ordre de l'image et du texte"
            ),
        ),
    ]
