# Generated by Django 4.1.7 on 2023-06-21 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0037_homesections"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homesections",
            name="text",
        ),
    ]
