# Generated by Django 4.1.7 on 2023-06-21 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0038_remove_homesections_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="homesections",
            old_name="name",
            new_name="name_ID",
        ),
    ]
