# Generated by Django 4.1.7 on 2023-06-21 13:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0040_aboutsections"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssoSections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ID", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                (
                    "richText",
                    ckeditor.fields.RichTextField(
                        default="Écrire ici",
                        max_length=10000,
                        verbose_name="Contenu de la section",
                    ),
                ),
                ("custom_html", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="", verbose_name="Image de la section"
                    ),
                ),
                ("image_title", models.CharField(blank=True, max_length=50)),
                ("image_alt", models.CharField(blank=True, max_length=50)),
                (
                    "reverse",
                    models.BooleanField(
                        default=False,
                        verbose_name="Inverser l'ordre de l'image et du texte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page association",
                "verbose_name_plural": "Page association",
            },
        ),
        migrations.AlterField(
            model_name="aboutsections",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="", verbose_name="Image de la section"
            ),
        ),
        migrations.AlterField(
            model_name="homesections",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="", verbose_name="Image de la section"
            ),
        ),
    ]
