# Generated by Django 4.1.7 on 2023-06-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0041_assosections_alter_aboutsections_image_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AboutPageSections",
        ),
        migrations.DeleteModel(
            name="AssociationSections",
        ),
        migrations.DeleteModel(
            name="HomePageSections",
        ),
    ]
