# Generated by Django 4.1.7 on 2023-06-27 05:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0042_remove_associationsections_homepagesections_ptr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssoStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Titre du statut"),
                ),
                ("text", ckeditor.fields.RichTextField(verbose_name="Texte du statut")),
            ],
            options={
                "verbose_name": "Statut de l'association",
                "verbose_name_plural": "Statuts de l'association",
            },
        ),
    ]
